fun main(){
    print("Enter your Enrollment No:")
    var stu  = readLine()?.toLong()
    print("Enter your Name:")
    var name = readLine()
    print("Enter your Branch:")
    var branch = readLine()
    print("Enter your Class:")
    var stuclass = readLine()
    print("Enter your Batch Name:")
    var batch = readLine()
    print("Enter you College Name:")
    var cname = readLine()
    print("Enter your University Name:")
    var uname = readLine()
    print("Enter your age:")
    var age = readLine()?.toInt()
    println()

    println("Student's Data:")
    println("Student Enrollment No: $stu")
    println("Student Name: $name")
    println("Student Branch: $branch")
    println("Student Class : $stuclass")
    println("Student Batch : $batch")
    println("Student College Name : $cname")
    println("Student University Name: $uname")
    println("Student Age: $age")
}